FROM registry.cn-hongkong.aliyuncs.com/velero/node:18-alpine

WORKDIR /app

# 复制package文件
COPY server/package*.json ./

# 安装依赖
RUN npm install --production

# 复制源代码
COPY server/ .

# 暴露端口
EXPOSE 3000

# 启动应用
CMD ["npm", "start"]